### PR TITLE
Updates to social system documentation

### PR DESCRIPTION
**Pull request by ZudoB**
Planning to document the following in full (or as close as i can get)

- [x] DMs
- [x] Notifications
- [x] Acknowledgements for DMs and notifications
- [x] Invites
- [x] Presence

### CODE REVIEW

**Comment by Poyo-SSB** [comment]
Hi! Thanks for your interest in contributing. Just for future reference, when contributing pull requests, you should do your work on a topic branch (as opposed to the master branch, which can cause issues).

**Comment by ZudoB** [comment]
> as opposed to the master branch, which can cause issues

Correct me if I'm wrong, but I'm pretty sure forked branches are completely separate until the PR is merged, no? I'd understand if I was committing directly to master on this repo, but I don't think it would be any different if I was committing to a different branch.

Either that or my understanding of git is flawed woomy

**Comment by Poyo-SSB** [comment]
I've made some edits, mostly with regards to style and terminology precision ("user" vs. "player" etc.). Furthermore, in `Data/Presence.md`, I removed the "the following values are only valid when `status` is [...]" because that's not necessarily the case and has little-to-no impact on the end user (as I understand it, at least. Correct me if I'm wrong).

Let me know if there are any last-minute revisions you'd like to make before I merge this.

**Comment by ZudoB** [comment]
Looking at tetrio.js, there's a couple of `switch` statements that are used to display the description in the social panel based on both the presence type and detail, and it won't output (for example) the TL status if your status isn't set to Busy. I'm not sure if it actually rejects it on the server side, but I'm sure that a user will never see an invalid status.

Up to you whether you want to change it though!

**Comment by Poyo-SSB** [comment]
Gotcha, makes sense—up to a dev to decide how they want to implement it.

Wrt master branches, it's just generally good form to use topic branches. When a maintainer checks out a PR for review, they do need to create a new local branch from the PR origin, and if the origin is `master` then they'll have to use a new name, which can be kind of annoying in CLI, especially when managing multiple PRs from multiple branches named `master`.

**Comment by ZudoB** [comment]
That makes a lot of sense, TIL

**Pull request merged**
