### PR TITLE
spelling mistakes

### PR DESCRIPTION
**Pull request by BumpyBill**

### CODE REVIEW

**Comment by Poyo-SSB** [comment]
Hi, thank you for contributing! In future, please PR from a topic branch rather than `master`. Makes things easier for repository maintainer and makes the Git history cleaner.

I've noticed that—in addition to spelling mistakes—you've also changed a lot of the style in some (but not all) documents? I'm assuming this was an automated mistake, especially since many hyphens have been changed to asterisks for some reason. In any case, I have a consistent style and I don't intend to change it, so I can't merge this PR unless the style changes are reverted.

**Comment by BumpyBill** [comment]
Right, sorry.

**Comment by Poyo-SSB** [comment]
Do you intend to fix this PR or will you make another?

**Comment by Poyo-SSB** [comment]
Closing as inactive.

**Pull request closed without merging**
